-- TULIPA · Carga inicial de 92 pessoas (people, não profiles)
-- Pessoas que participam ou participaram do projeto, gerenciadas pela Secretaria.
-- Roda no SQL Editor uma única vez. Pra rerodar, primeiro: delete from public.people;
--
-- 13 pessoas estão sem telefone (marcadas como "Ainda está no projeto?" pelo
-- Gabriel) — entram com phone NULL e uma nota interna pra Secretaria confirmar.

insert into public.people (full_name, phone, notes, is_active) values
  ('Alanne Almeida de Oliveira Freitas',                '(81) 99326-6003', null,                                  true),
  ('Arthur de Assis Souza',                             '(81) 98621-8000', null,                                  true),
  ('Arthur Hilton Trindade Gomes',                      '(81) 99564-8949', null,                                  true),
  ('Arthur Ramiro Soares',                              '(81) 99463-8710', null,                                  true),
  ('Artur Coutinho Cavalcante',                         '(81) 98831-1800', null,                                  true),
  ('Ana Helena Mendonça Moreira',                       '(81) 98852-2256', null,                                  true),
  ('Ana Luísa do Rego Barros Fonseca',                  null,              'Status no projeto a confirmar',       true),
  ('Ana Luiza Quirino do Nascimento',                   '(11) 95870-8507', null,                                  true),
  ('Ana Maria Rodrigues de Lira Vaz',                   '(81) 98632-3346', null,                                  true),
  ('Anália Thallyta Almeida de Brito Nunes',            '(87) 99961-6046', null,                                  true),
  ('Beatriz Cordeiro de Araújo',                        '(81) 99959-5773', null,                                  true),
  ('Beatriz Oliveira do Nascimento',                    '(81) 99291-2279', null,                                  true),
  ('Bernardo José Magalhães Porto Oliveira',            '(87) 99139-0188', null,                                  true),
  ('Bernardo Marques Callado',                          '(81) 99686-5474', null,                                  true),
  ('Caio Rodrigues Moreira',                            '(81) 92002-3498', null,                                  true),
  ('Caio Magalhães Moura',                              '(81) 99113-8562', null,                                  true),
  ('Chloe Brandão Sellemann',                           '(81) 99987-0557', null,                                  true),
  ('Camile Alves de Lima',                              '(81) 99563-7579', null,                                  true),
  ('Clara Bueno',                                       '(81) 98582-1074', null,                                  true),
  ('Clara Kamilly dos Santos Fares',                    '(81) 99702-6672', null,                                  true),
  ('Cleber de Almeida Franco',                          '(11) 95455-9165', null,                                  true),
  ('Cora Nicoleli Adrião',                              '(81) 99597-0467', null,                                  true),
  ('Danilo da Silva Medeiros',                          '(81) 99381-2347', null,                                  true),
  ('Diana de Melo de Souza',                            '(81) 98266-1818', null,                                  true),
  ('Diego Teixeira da Silva Mello',                     '(71) 99980-8125', null,                                  true),
  ('Enilly França Campos',                              '(81) 99969-2310', null,                                  true),
  ('Estefanny Rodrigues Pereira de Andrade',            '(81) 99966-8708', null,                                  true),
  ('Gabriel Ângelo',                                    '(81) 99385-8453', null,                                  true),
  ('Gabriela Ribeiro de Queiroz',                       '(81) 98904-9389', null,                                  true),
  ('George Luiz Peixoto Cavalcanti Júnior',             null,              'Status no projeto a confirmar',       true),
  ('Getúlio Igor Alencar Specht da Costa',              '(81) 99954-1943', null,                                  true),
  ('Girlan Souza Silva',                                null,              'Status no projeto a confirmar',       true),
  ('Hanna Luiza Souza Alves',                           '(81) 99409-3986', null,                                  true),
  ('Heloísa Guedes dos Santos',                         '(81) 99915-3475', null,                                  true),
  ('Iara Loren',                                        '(81) 99807-1437', null,                                  true),
  ('Ivi Silva Anunciação',                              '(73) 99109-7128', null,                                  true),
  ('João Marcelo Melo',                                 '(81) 99184-9126', null,                                  true),
  ('José Arthur Gabriel Felix Moreira de Lemos',        '(81) 98209-2208', null,                                  true),
  ('Júlia Patrícia Gonçalves da Silva',                 '(81) 98946-6695', null,                                  true),
  ('Juliana Cintra de Amorim',                          '(81) 98986-5256', null,                                  true),
  ('Júlio César Aryosto Mendes dos Santos',             '(81) 99871-9202', null,                                  true),
  ('Kamylle de Holanda Cabral',                         null,              'Status no projeto a confirmar',       true),
  ('Lana Suely da Silva',                               '(81) 98306-2561', null,                                  true),
  ('Lara Priscila Bezerra de Araújo',                   null,              'Status no projeto a confirmar',       true),
  ('Larissa Leal Cabral Rodrigues',                     '(81) 99501-6961', null,                                  true),
  ('Letícia Costa Moura',                               null,              'Status no projeto a confirmar',       true),
  ('Leonardo Arthur Ribeiro',                           '(81) 99643-4181', null,                                  true),
  ('Luan Gabriel Ermírio da Luz Silva',                 null,              'Status no projeto a confirmar',       true),
  ('Luana Souza Zschaber Roichman',                     '(81) 99871-5518', null,                                  true),
  ('Lucas Simões Cezar Menezes Gottschall',             '(81) 99660-9924', null,                                  true),
  ('Luísa Torres Marques da Silva',                     '(81) 99987-7449', null,                                  true),
  ('Luma Alves Rodrigues',                              '(82) 99918-1334', null,                                  true),
  ('Marcela Souza Dantas',                              '(81) 99756-0740', null,                                  true),
  ('Maria Eduarda Costa e Silva',                       '(81) 98104-0880', null,                                  true),
  ('Maria Eduarda Gusmão de Gouveia Brandão',           '(81) 99989-9220', null,                                  true),
  ('Maria Emília de França Bezerra Leite',              '(81) 99572-7955', null,                                  true),
  ('Maria Fernanda Cardoso',                            '(81) 97911-8167', null,                                  true),
  ('Maria Joana Cabral Souza',                          '(81) 99670-0630', null,                                  true),
  ('Maria Júlia Caluete Gomes de Azevedo Dias',         null,              'Status no projeto a confirmar',       true),
  ('Maria Letícia de Araújo Rocha',                     '(81) 98883-8783', null,                                  true),
  ('Maria Luíza Lapa',                                  '(81) 99774-0930', null,                                  true),
  ('Marly Pedroza de Albuquerque',                      '(81) 99217-8010', null,                                  true),
  ('Mariana Porto Costa',                               '(81) 99591-3183', null,                                  true),
  ('Mariana Silva San Martin',                          null,              'Status no projeto a confirmar',       true),
  ('Marina Albuquerque de Andrade',                     '(81) 98233-3105', null,                                  true),
  ('Marina de Sousa Costa',                             '(81) 99642-9420', null,                                  true),
  ('Marina Figueirôa Lima',                             '(81) 99109-3040', null,                                  true),
  ('Marina Oertli Martinez',                            '(81) 99282-8646', null,                                  true),
  ('Matheus Mendez de Vasconcelos',                     '(81) 99848-9986', null,                                  true),
  ('Mayara Barbosa de Cunha',                           '(81) 99760-5941', null,                                  true),
  ('Millena Oliveira Barata',                           '(81) 98238-8616', null,                                  true),
  ('Mirella Oliveira',                                  null,              'Status no projeto a confirmar',       true),
  ('Nathália Martins de Medeiros',                      null,              'Status no projeto a confirmar',       true),
  ('Nicolas Domingues Dias',                            '(81) 98146-1535', null,                                  true),
  ('Paula de Assis Ramos',                              '(81) 98141-1937', null,                                  true),
  ('Paulo Macedo Furtado da Silva',                     '(81) 99577-1464', null,                                  true),
  ('Pedro Emmanuel Tavares',                            '(81) 99778-0480', null,                                  true),
  ('Rafaelle Agustinho da Silva',                       '(81) 99589-3060', null,                                  true),
  ('Renan Marques Franklin',                            '(41) 99163-8662', null,                                  true),
  ('Renata Oliveira Tavares',                           '(81) 99617-4570', null,                                  true),
  ('Rodrigo Coutinho Pereira',                          '(81) 99646-4707', null,                                  true),
  ('Ruan Pina de Oliveira',                             '(81) 98101-4216', null,                                  true),
  ('Sarah Gabriela Brito de Morais',                    '(81) 99611-1219', null,                                  true),
  ('Suzana de Abreu e Lima',                            '(81) 99910-2006', null,                                  true),
  ('Talita Maria Cordeiro Santos Silva',                '(81) 99646-7372', null,                                  true),
  ('Thamires Freire de Cerqueira Silva',                null,              'Status no projeto a confirmar',       true),
  ('Thaíssa Mickaelle dos Santos Silva',                null,              'Status no projeto a confirmar',       true),
  ('Thaylan Wambert da Silva Borba',                    '(81) 98241-2337', null,                                  true),
  ('Thaynná Pinheiro Rodrigues de Oliveira',            '(81) 99891-7817', null,                                  true),
  ('Vinicius Rocha Medeiros',                           '(81) 99899-7220', null,                                  true),
  ('Vitória Maria Lima Antunes',                        '(81) 99921-0393', null,                                  true),
  ('Yasmin Evelyn do Prado Moura',                      '(81) 99915-9365', null,                                  true);

-- Confirma contagem
select count(*) as total_pessoas, count(phone) as com_telefone, count(*) filter (where notes is not null) as a_confirmar
  from public.people;
