// Schema da página Home. Define os blocos visíveis no editor, com labels humanos.
// Cada field aponta pra um data-edit-id real no HTML.
//
// types:
//   'text'        — uma linha, sem formatação
//   'rich'        — multi-linha, aceita markdown leve (**negrito**, *itálico*)
//   'link-label'  — texto puro do link (preserva atributos como href)

export const HOME_SCHEMA = {
  scope: 'global',
  label: 'Página inicial',
  iconName: 'brand',
  blocks: [
    {
      id: 'hero',
      sectionId: 'section.hero',
      iconName: 'hero',
      label: 'Capa',
      description: 'O topo da home: logo, título TULIPA, manifesto curto e botões.',
      summaryFields: ['hero.title-line', 'hero.lede'],
      fields: [
        { id: 'hero.eyebrow',       label: 'Eyebrow (linha pequena acima do título)', type: 'text' },
        { id: 'hero.title-line',    label: 'Frase antes do nome TULIPA',              type: 'text' },
        { id: 'hero.sub',           label: 'Subtítulo (em itálico, abaixo do nome)',  type: 'rich' },
        { id: 'hero.lede',          label: 'Parágrafo de boas-vindas',                type: 'rich' },
        { id: 'hero.cta-primary',   label: 'Botão principal — texto',                 type: 'link-label' },
        { id: 'hero.cta-instagram', label: 'Botão Instagram — texto',                 type: 'link-label' },
        { id: 'hero.scroll-word',   label: 'Frase decorativa de scroll (rodapé da capa)', type: 'text' },
      ],
    },
    {
      id: 'marquee',
      sectionId: 'section.marquee',
      iconName: 'marquee',
      label: 'Carrossel de conceitos junguianos',
      description: 'A faixa rolante com palavras-chave (Self, Sombra, Anima…). Por enquanto só permite ocultar / reordenar.',
      summaryFields: [],
      fields: [],
    },
    {
      id: 'manifesto',
      sectionId: 'section.manifesto',
      iconName: 'manifesto',
      label: 'Manifesto',
      description: 'Citação central em pergaminho, com folhas decorativas.',
      summaryFields: ['manifesto.body'],
      fields: [
        { id: 'manifesto.body',        label: 'Citação principal',     type: 'rich' },
        { id: 'manifesto.attribution', label: 'Atribuição (linha de baixo)', type: 'text' },
      ],
    },
    {
      id: 'sobre',
      sectionId: 'section.sobre',
      iconName: 'sobre',
      label: 'Quem somos',
      description: 'Apresentação do projeto — texto editorial.',
      summaryFields: ['sobre.title', 'sobre.p1'],
      fields: [
        { id: 'sobre.eyebrow', label: 'Eyebrow',           type: 'text' },
        { id: 'sobre.title',   label: 'Título da seção',   type: 'rich' },
        { id: 'sobre.p1',      label: 'Parágrafo 1',       type: 'rich' },
        { id: 'sobre.p2',      label: 'Parágrafo 2',       type: 'rich' },
        { id: 'sobre.p3',      label: 'Parágrafo 3',       type: 'rich' },
      ],
    },
    {
      id: 'missao',
      sectionId: 'section.missao',
      iconName: 'missao',
      label: 'Nossa missão',
      description: 'Citação grande seguida de 3 pilares: Propagar · Aprofundar · Acolher.',
      summaryFields: ['missao.title'],
      fields: [
        { id: 'missao.eyebrow', label: 'Eyebrow',                type: 'text' },
        { id: 'missao.title',   label: 'Citação grande (centro)', type: 'rich' },
        { id: 'missao.pillar.propagar.title',   label: 'Pilar 1 — título',  type: 'text' },
        { id: 'missao.pillar.propagar.body',    label: 'Pilar 1 — texto',   type: 'rich' },
        { id: 'missao.pillar.aprofundar.title', label: 'Pilar 2 — título',  type: 'text' },
        { id: 'missao.pillar.aprofundar.body',  label: 'Pilar 2 — texto',   type: 'rich' },
        { id: 'missao.pillar.acolher.title',    label: 'Pilar 3 — título',  type: 'text' },
        { id: 'missao.pillar.acolher.body',     label: 'Pilar 3 — texto',   type: 'rich' },
      ],
    },
    {
      id: 'nome',
      sectionId: 'section.nome',
      iconName: 'nome',
      label: 'O nome (T·U·LI·P·A)',
      description: 'Acrônimo + frase simbólica explicando o nome do projeto.',
      summaryFields: ['nome.title'],
      fields: [
        { id: 'nome.eyebrow',   label: 'Eyebrow',                  type: 'text' },
        { id: 'nome.title',     label: 'Pergunta principal',       type: 'rich' },
        { id: 'nome.acronym.T', label: 'T —',                      type: 'text' },
        { id: 'nome.acronym.U', label: 'U —',                      type: 'text' },
        { id: 'nome.acronym.LI', label: 'LI —',                    type: 'text' },
        { id: 'nome.acronym.P', label: 'P —',                      type: 'text' },
        { id: 'nome.acronym.A', label: 'A —',                      type: 'text' },
        { id: 'nome.full',      label: 'Nome completo (linha)',    type: 'text' },
        { id: 'nome.quote',     label: 'Citação simbólica abaixo', type: 'rich' },
      ],
    },
    {
      id: 'atividades',
      sectionId: 'section.atividades',
      iconName: 'atividades',
      label: 'Atividades',
      description: '4 cards: Grupos de Estudo, Leitura Conjunta, Arteterapia, Allos.',
      summaryFields: ['atividades.title'],
      fields: [
        { id: 'atividades.eyebrow', label: 'Eyebrow',           type: 'text' },
        { id: 'atividades.title',   label: 'Título da seção',   type: 'rich' },
        { id: 'atividades.card.grupos.title',  label: 'Card 1 — título',  type: 'rich' },
        { id: 'atividades.card.grupos.body',   label: 'Card 1 — texto',   type: 'rich' },
        { id: 'atividades.card.leitura.title', label: 'Card 2 — título',  type: 'rich' },
        { id: 'atividades.card.leitura.body',  label: 'Card 2 — texto',   type: 'rich' },
        { id: 'atividades.card.arte.title',    label: 'Card 3 — título',  type: 'rich' },
        { id: 'atividades.card.arte.body',     label: 'Card 3 — texto',   type: 'rich' },
        { id: 'atividades.card.allos.title',   label: 'Card 4 — título',  type: 'rich' },
        { id: 'atividades.card.allos.body',    label: 'Card 4 — texto',   type: 'rich' },
      ],
    },
    {
      id: 'departamentos',
      sectionId: 'section.departamentos',
      iconName: 'departamentos',
      label: 'Departamentos',
      description: 'Hierarquia em árvore: 3 cargos no topo + 4 departamentos abaixo.',
      summaryFields: ['depts.title', 'depts.intro'],
      fields: [
        { id: 'depts.eyebrow', label: 'Eyebrow',         type: 'text' },
        { id: 'depts.title',   label: 'Título da seção', type: 'rich' },
        { id: 'depts.intro',   label: 'Texto introdutório', type: 'rich' },
        { id: 'depts.lead.prof-orientador.label', label: 'Cargo topo 1 (esquerda)', type: 'link-label' },
        { id: 'depts.lead.presidencia.label',     label: 'Cargo topo 2 (centro)',   type: 'link-label' },
        { id: 'depts.lead.prof-colaborador.label',label: 'Cargo topo 3 (direita)',  type: 'link-label' },
        { id: 'depts.dept.midia.label',           label: 'Departamento 1',          type: 'link-label' },
        { id: 'depts.dept.pesquisa.label',        label: 'Departamento 2',          type: 'link-label' },
        { id: 'depts.dept.tesouraria.label',      label: 'Departamento 3',          type: 'link-label' },
        { id: 'depts.dept.secretaria.label',      label: 'Departamento 4',          type: 'link-label' },
      ],
    },
    {
      id: 'pullquote',
      sectionId: 'section.pullquote',
      iconName: 'pullquote',
      label: 'Citação intermediária',
      description: 'Frase inspirada em Jung entre as seções de departamentos e contato.',
      summaryFields: ['pullquote.body'],
      fields: [
        { id: 'pullquote.body',   label: 'Citação',     type: 'rich' },
        { id: 'pullquote.author', label: 'Atribuição',  type: 'text' },
      ],
    },
    {
      id: 'contato',
      sectionId: 'section.contato',
      iconName: 'contato',
      label: 'Contato',
      description: '3 vias de contato: Instagram, endereço UNICAP e e-mail. Mais o selo com citação.',
      summaryFields: ['contato.title', 'contato.body'],
      fields: [
        { id: 'contato.eyebrow', label: 'Eyebrow',          type: 'text' },
        { id: 'contato.title',   label: 'Título da seção',  type: 'rich' },
        { id: 'contato.body',    label: 'Parágrafo introdutório', type: 'rich' },
        { id: 'contato.link.instagram.title', label: 'Instagram — título', type: 'text' },
        { id: 'contato.link.instagram.sub',   label: 'Instagram — descrição', type: 'text' },
        { id: 'contato.link.endereco.title',  label: 'Endereço — título',  type: 'text' },
        { id: 'contato.link.endereco.sub',    label: 'Endereço — descrição', type: 'text' },
        { id: 'contato.link.email.title',     label: 'E-mail — título',    type: 'text' },
        { id: 'contato.link.email.sub',       label: 'E-mail — descrição', type: 'text' },
        { id: 'contato.card.quote',           label: 'Citação no selo',    type: 'rich' },
      ],
    },
  ],
};

export function blockById(blockId) {
  return HOME_SCHEMA.blocks.find((b) => b.id === blockId);
}
